Update patch set 2
Patch Set 2: Code-Review-1

Huh?! Why would the removal of "final" cause this: TestWatcher: Test failed: test(org.opendaylight.controller.test.sal.binding.it.DataServiceIT)
java.lang.IllegalAccessException: Class org.apache.aries.proxy.impl.ProxyHandler$1 can not access a member of class org.opendaylight.controller.md.sal.binding.impl.BindingToNormalizedNodeCodec with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)[:1.8.0_101]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)[:1.8.0_101]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)[:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:491)[:1.8.0_101]
	at org.apache.aries.proxy.impl.ProxyHandler$1.invoke(ProxyHandler.java:54)

Patch-set: 2
Label: Code-Review=-1