Update patch set 24
Patch Set 24:

I tried these changes in a 3-node setup. I created an item on the leader and got this error when applying the state during replication on a follower:

java.lang.IllegalStateException: Apply strategy failed to produce root node
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)[114:com.google.guava:18.0.0]
        at org.opendaylight.yangtools.yang.data.impl.schema.tree.AbstractDataTreeTip.prepare(AbstractDataTreeTip.java:54)[138:org.opendaylight.yangtools.yang-data-impl:0.7.0.SNAPSHOT]
        at org.opendaylight.controller.cluster.datastore.ShardDataTree.applyForeignCandidate(ShardDataTree.java:162)[234:org.opendaylight.controller.sal-distributed-datastore:1.2.0.SNAPSHOT]
        at org.opendaylight.controller.cluster.datastore.Shard.applyState(Shard.java:580)[234:org.opendaylight.controller.sal-distributed-datastore:1.2.0.SNAPSHOT]
        at org.opendaylight.controller.cluster.raft.RaftActor.handleCommand(RaftActor.java:212)[227:org.opendaylight.controller.sal-akka-raft:1.2.0.SNAPSHOT]

Patch-set: 24
Label: Verified=0