Update patch set 1
Patch Set 1: Code-Review-1

This breaks end  to end.  When I rebase it onto master and plug it into master on the OFplugin, it breaks, and no augmentations (or it seems children) are visible in the inventory for RESTCONF.

Please fix and resubmit.  I am marking this as -1 because it should not be merged in its current form.

On the OSGI console I see this output:

2013-12-06 10:25:53.660 PST [pool-18-thread-25] INFO  o.o.c.m.s.c.i.service.TwoPhaseCommit - Transaction: BA-39 Started.
2013-12-06 10:25:53.660 PST [pool-16-thread-2] INFO  o.o.c.sal.binding.impl.NotifyTask - Notification delivered NodeConnectorUpdated [_nodeConnectorRef=NodeConnectorRef [_value=InstanceIdentifier [path=[org.opendaylight.yang.gen.v1.urn.opendaylight.inventory.rev130819.Nodes, org.opendaylight.yang.gen.v1.urn.opendaylight.inventory.rev130819.nodes.Node[key=NodeKey [_id=Uri [_value=openflow:3]]], org.opendaylight.yang.gen.v1.urn.opendaylight.inventory.rev130819.node.NodeConnector[key=NodeConnectorKey [_id=Uri [_value=openflow:3:2]]]]]], _id=Uri [_value=openflow:3:2]] to org.opendaylight.controller.sal.compatibility.InventoryAndReadAdapter$$Broker$ListenerInvoker@12025a1
2013-12-06 10:25:53.662 PST [pool-18-thread-8] ERROR o.o.c.m.s.c.i.service.TwoPhaseCommit - Transaction: BA-19 Request Commit failed
java.lang.TypeNotPresentException: Type org.opendaylight.yang.gen.v1.urn.opendaylight.inventory.rev130819.node.NodeConnector not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[na:1.7.0_25]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[na:1.7.0_25]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:1.7.0_25]
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[na:1.7.0_25]
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[na:1.7.0_25]
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[na:1.7.0_25]
	at sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:100) ~[na:1.7.0_25]
	at java.lang.Class.getGenericInterfaces(Class.java:814) ~[na:1.7.0_25]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.LazyGeneratedCodecRegistry.getAugmentableArgumentFrom(LazyGeneratedCodecRegistry.java:150) ~[na:na]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.LazyGeneratedCodecRegistry.getCodecForAugmentation(LazyGeneratedCodecRegistry.java:138) ~[na:na]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.LazyGeneratedCodecRegistry$AugmentableCompositeCodec.serializeImpl(LazyGeneratedCodecRegistry.java:812) ~[na:na]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.LazyGeneratedCodecRegistry$AugmentableCompositeCodec.serialize(LazyGeneratedCodecRegistry.java:791) ~[na:na]
	at org.opendaylight.yang.gen.v1.urn.opendaylight.inventory.rev130819.node.NodeConnector$Broker$Codec$DOM.toDomStatic(NodeConnector$Broker$Codec$DOM.java) ~[na:na]
	at org.opendaylight.yang.gen.v1.urn.opendaylight.inventory.rev130819.node.NodeConnector$Broker$Codec$DOM.serialize(NodeConnector$Broker$Codec$DOM.java) ~[na:na]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.LazyGeneratedCodecRegistry$IntermediateCodec.serialize(LazyGeneratedCodecRegistry.java:468) ~[na:na]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.LazyGeneratedCodecRegistry$DataContainerCodecImpl.serialize(LazyGeneratedCodecRegistry.java:516) ~[na:na]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.RuntimeGeneratedMappingServiceImpl.toCompositeNodeImpl(RuntimeGeneratedMappingServiceImpl.java:254) ~[na:na]
	at org.opendaylight.controller.sal.binding.dom.serializer.impl.RuntimeGeneratedMappingServiceImpl.toDataDom(RuntimeGeneratedMappingServiceImpl.java:240) ~[na:na]
	at org.opendaylight.controller.sal.binding.impl.connect.dom.BindingIndependentDataServiceConnector.createBindingToDomTransaction(BindingIndependentDataServiceConnector.java:109) ~[na:na]
	at org.opendaylight.controller.sal.binding.impl.connect.dom.BindingIndependentDataServiceConnector.access$400(BindingIndependentDataServiceConnector.java:35) ~[na:na]
	at org.opendaylight.controller.sal.binding.impl.connect.dom.BindingIndependentDataServiceConnector$BindingToDomCommitHandler.requestCommit(BindingIndependentDataServiceConnector.java:314) ~[na:na]
	at org.opendaylight.controller.md.sal.common.impl.service.TwoPhaseCommit.call(TwoPhaseCommit.java:76) ~[na:na]
	at org.opendaylight.controller.md.sal.common.impl.service.TwoPhaseCommit.call(TwoPhaseCommit.java:31) ~[na:na]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.7.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.7.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_25]

Patch-set: 1
Label: Code-Review=-1