WIP: Migrate to Apache Pekko
// FIXME
[ERROR] org.opendaylight.controller.cluster.raft.RaftActorLeadershipTransferCohortTest.testPauseLeaderTimeout -- Time elapsed: 9.144 s <<< ERROR!
java.lang.RuntimeException: java.lang.AssertionError: Identify returned non-present
        at org.opendaylight.controller.cluster.raft.TestActorFactory.verifyActorReady(TestActorFactory.java:164)
        at org.opendaylight.controller.cluster.raft.TestActorFactory.addActor(TestActorFactory.java:135)
        at org.opendaylight.controller.cluster.raft.TestActorFactory.createTestActor(TestActorFactory.java:109)
        at org.opendaylight.controller.cluster.raft.RaftActorLeadershipTransferCohortTest.setup(RaftActorLeadershipTransferCohortTest.java:44)
        at org.opendaylight.controller.cluster.raft.RaftActorLeadershipTransferCohortTest.testPauseLeaderTimeout(RaftActorLeadershipTransferCohortTest.java:94)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: java.lang.AssertionError: Identify returned non-present
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.opendaylight.controller.cluster.raft.TestActorFactory.verifyActorReady(TestActorFactory.java:156)
        ... 5 more

https://pekko.apache.org/docs/pekko/current/project/migration-guides.html

JIRA: CONTROLLER-2120
Change-Id: I2c71d939dbf7fb277e03a85de4ca04b9333ff211
Signed-off-by: Ivan Hrasko <ivan.hrasko@pantheon.tech>