Update patch set 3
Patch Set 3:

> > This commit broke the use of KARAF_DEBUG environment variable set
 > > to 1 to enable debugging in Karaf. I get this:
 > >
 > > karaf: Enabling Java debug options: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
 > > ERROR: transport error 202: bind failed: Can't assign requested
 > > address
 > > ERROR: JDWP Transport dt_socket failed to initialize,
 > > TRANSPORT_INIT(510)
 > > JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports
 > > initialized [debugInit.c:750]
 > > FATAL ERROR in native method: JDWP No transports initialized,
 > > jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
 > >
 > > Reverting this patch fixes this. I haven't looked into the root
 > > cause, can some please take a look?
 > 
 > Hi Lori,
 > 
 > Thanks for the feedback. Actually I found a mistake in the patch
 > and I'm going to fix it. I deleted a blank space wrongly and it
 > passed Jenkins executions.
 > 
 > Sorry for disturbances.

It's not just the space. I was hoping it's only that, but adding the space didn't fix things for me, I also needed to remove the quotes from JAVA_OPTS

Patch-set: 3