Update patch set 2
Patch Set 2: Code-Review+1

I tested with this patch I don't get the exception reported in bug anymore. However now it is actually writing to store it is generating lot of warnings. May not be issue but just an observation:

2014-08-21 11:58:49.295 PDT [pool-10-thread-1] WARN  o.o.c.m.s.d.s.i.InMemoryDOMDataStore - Store Tx: DOM-OPER-172 Conflicting modification for (urn:opendaylight:inventory?revision=2013-08-19)nodes/(urn:opendaylight:inventory?revision=2013-08-19)node/(urn:opendaylight:inventory?revision=2013-08-19)node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2}]/(urn:opendaylight:inventory?revision=2013-08-19)node-connector/(urn:opendaylight:inventory?revision=2013-08-19)node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2:2}].
2014-08-21 11:58:49.343 PDT [md-sal-binding-notification-8] INFO  o.o.l.flow.FlowWriterServiceImpl - In addMacToMacFlowsUsingShortestPath: No flows added. Source and Destination ports are same.
2014-08-21 11:58:49.344 PDT [WriteTxCommit-0] WARN  o.o.c.m.s.d.b.i.DOMDataCommitCoordinatorImpl - Tx: DOM-170 Error during phase CAN_COMMIT, starting Abort
org.opendaylight.controller.md.sal.common.api.data.OptimisticLockFailedException: Optimistic lock failed.
        at org.opendaylight.controller.md.sal.dom.store.impl.InMemoryDOMDataStore$ThreePhaseCommitImpl$1.call(InMemoryDOMDataStore.java:366) ~[na:na]
        at org.opendaylight.controller.md.sal.dom.store.impl.InMemoryDOMDataStore$ThreePhaseCommitImpl$1.call(InMemoryDOMDataStore.java:356) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
Caused by: org.opendaylight.yangtools.yang.data.api.schema.tree.ConflictingModificationAppliedException: Node was replaced by other transaction.
        at org.opendaylight.yangtools.yang.data.impl.schema.tree.SchemaAwareApplyOperation.checkConflicting(SchemaAwareApplyOperation.java:79) ~[na:na]
        at

Patch-set: 2
Label: Code-Review=+1