Update patch set 1
Patch Set 1: Code-Review-1

Oups... I misinterpreted what happened here!  It's not "failing fast" if there is a NoClassDefFoundError, but using systemTimeout, with whatever value, simply BREAKS all tests, they all fail with some java.rmi.NotBoundException! :-(

Could be a bug in pax exam? This is with 4.4.0; latest is 4.9.1, we attempted to upgrade a few weeks ago but ran into trouble and had to revert.  I'll re-try that some time, and then get back to this one again.

PARKING this for now.

Patch-set: 1
Reviewer: Gerrit User 5867 <5867@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-1