Add 1 minute systemTimeout TimeoutOption to AbstractConfigTestBase
All other changes are just minor Checkstyle formatting changes, sorry
for throwing them in together.

Without a systemTimeout TimeoutOption, a failure such as the one shown
below blocks an *IT for 06:32 min.  With this option, it "fails fast" in
16s (note not 1 minute; it appears that that the mere presence of this
option makes it check more eagerly if something went wrong).

opendaylight-user@root>2016-08-11 20:52:35,287 | ERROR | BundleWatcher:
1 | BundleWatcher                    | 46 -
org.ops4j.pax.swissbox.extender - 1.8.0 | Exception in executor thread
java.lang.NoClassDefFoundError:
org/opendaylight/controller/mdsal/it/base/AbstractMdsalTestBase
	at java.lang.ClassLoader.defineClass1(Native Method)[:1.8.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)[:1.8.0_101]
	at
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
	at
org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClassHoldingLock(ClasspathManager.java:632)
	at
org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:607)
	at
org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:568)
	at
org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:492)
	at
org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:465)
	at
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
	at
org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at
org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
	at
org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at
org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_101]
	at
org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:340)
	at
org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:229)
	at
org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1212)
	at
org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvoker.<init>(JUnitProbeInvoker.java:65)
	at
org.ops4j.pax.exam.invoker.junit.internal.JUnitProbeInvokerFactory.createProbeInvoker(JUnitProbeInvokerFactory.java:36)
	at
org.ops4j.pax.exam.raw.extender.intern.Parser.createInvoker(Parser.java:81)
	at org.ops4j.pax.exam.raw.extender.intern.Parser.make(Parser.java:68)
	at org.ops4j.pax.exam.raw.extender.intern.Parser.<init>(Parser.java:54)
	at
org.ops4j.pax.exam.raw.extender.intern.TestBundleObserver.addingEntries(TestBundleObserver.java:69)
	at
org.ops4j.pax.swissbox.extender.BundleWatcher$3.run(BundleWatcher.java:226)[46:org.ops4j.pax.swissbox.extender:1.8.0]
	at
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_101]
	at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_101]
	at
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_101]
	at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_101]
	at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_101]
Caused by: java.lang.ClassNotFoundException:
org.opendaylight.controller.mdsal.it.base.AbstractMdsalTestBase
	at
org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)[org.eclipse.osgi-3.8.2.v20130124-134944.jar:]
	at
org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)[org.eclipse.osgi-3.8.2.v20130124-134944.jar:]
	at
org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)[org.eclipse.osgi-3.8.2.v20130124-134944.jar:]
	at
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)[org.eclipse.osgi-3.8.2.v20130124-134944.jar:]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_101]
	... 32 more


Change-Id: I2374686c6978b7cf786049b6102afe395a5c173e
Signed-off-by: Michael Vorburger <vorburger@redhat.com>