Update patch set 5
Patch Set 5:

After installing odl-all, and trying to open localhost:8080 I see the following in the log:

2014-05-09 09:36:22,556 | WARN  | Local user karaf | hMatchingResourcePatternResolver | 96 - org.springframework.core - 3.1.3.RELEASE | Cannot search for matching files underneath URL [bundleresource://202.fwk776493144/org/opendaylight/controller/topology/web/] because it does not correspond to a directory in the file system
java.io.FileNotFoundException: URL [bundleresource://202.fwk776493144/org/opendaylight/controller/topology/web/] cannot be resolved to absolute file path because it does not reside in the file system: bundleresource://202.fwk776493144/org/opendaylight/controller/topology/web/
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:205)[96:org.springframework.core:3.1.3.RELEASE]

The ODL web console does not load.

Patch-set: 5
Label: Verified=0