Update patch set 6
Patch Set 6:

(1 comment)

When I build and then

cd opendaylight/distribution/opendaylight-karaf/target/assembly/bin
sh karaf

I both do not see the new branding, but I also get an exception:

karaf@root()> Exception in thread "JMX Connector Thread [service:jmx:rmi://0.0.0.0:44444/jndi/rmi://0.0.0.0:1099/karaf-root]" java.lang.RuntimeException: Could not start JMX connector server
	at org.apache.karaf.management.ConnectorServerFactory$1.run(ConnectorServerFactory.java:258)
Caused by: java.io.IOException: Cannot bind to URL [rmi://0.0.0.0:1099/karaf-root]: javax.naming.ConfigurationException [Root exception is java.rmi.UnknownHostException: Unknown host: 0.0.0.0; nested exception is: 
	java.net.UnknownHostException: EAW-M-57QR.CISCO.COM: EAW-M-57QR.CISCO.COM: nodename nor servname provided, or not known]
	at javax.management.remote.rmi.RMIConnectorServer.newIOException(RMIConnectorServer.java:826)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:431)
	at org.apache.karaf.management.ConnectorServerFactory$1.run(ConnectorServerFactory.java:245)
Caused by: javax.naming.ConfigurationException [Root exception is java.rmi.UnknownHostException: Unknown host: 0.0.0.0; nested exception is: 
	java.net.UnknownHostException: EAW-M-57QR.CISCO.COM: EAW-M-57QR.CISCO.COM: nodename nor servname provided, or not known]
	at com.sun.jndi.rmi.registry.RegistryContext.bind(RegistryContext.java:143)
	at com.sun.jndi.toolkit.url.GenericURLContext.bind(GenericURLContext.java:226)
	at javax.naming.InitialContext.bind(InitialContext.java:419)
	at javax.management.remote.rmi.RMIConnectorServer.bind(RMIConnectorServer.java:643)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:426)
	... 1 more
Caused by: java.rmi.UnknownHostException: Unknown host: 0.0.0.0; nested exception is: 
	java.net.UnknownHostException: EAW-M-57QR.CISCO.COM: EAW-M-57QR.CISCO.COM: nodename nor servname provided, or not known
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:616)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:341)
	at sun.rmi.registry.RegistryImpl_Stub.bind(Unknown Source)
	at com.sun.jndi.rmi.registry.RegistryContext.bind(RegistryContext.java:137)
	... 5 more
Caused by: java.net.UnknownHostException: EAW-M-57QR.CISCO.COM: EAW-M-57QR.CISCO.COM: nodename nor servname provided, or not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:198)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:208)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:147)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 10 more
Caused by: java.net.UnknownHostException: EAW-M-57QR.CISCO.COM: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
	... 20 more

Patch-set: 6
Label: Verified=0