Update patch set 8
Patch Set 8:

On a side note, an unrelated test failed:

java.lang.AssertionError: expected:<3> but was:<2>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at org.opendaylight.controller.cluster.raft.RaftActorTest$13.<init>(RaftActorTest.java:894)
        at org.opendaylight.controller.cluster.raft.RaftActorTest.testRaftRoleChangeNotifier(RaftActorTest.java:881)

Looks like it didn't get the role change to Leader in time. That can be fixed in another patch.

Patch-set: 8