WIP: handle Failed state
Our unit tests show this splat:

10:53:07,17 PM [cluster-test-akka.actor.default-dispatcher-16] [ERROR] ConcurrentDOMDataBroker - Tx: DOM-CHAIN-0-0 Error during Abort.
java.lang.IllegalStateException: member-1-datastore-testChainedTransactionFailureWithMultipleShards-fe-0-chn-1-txn-0-2 expect to be ready, is in state FAILED (CanCommit failed)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at org.opendaylight.controller.cluster.datastore.FrontendReadWriteTransaction.checkReady(FrontendReadWriteTransaction.java:566)
	at org.opendaylight.controller.cluster.datastore.FrontendReadWriteTransaction.handleTransactionAbort(FrontendReadWriteTransaction.java:313)
	at org.opendaylight.controller.cluster.datastore.FrontendReadWriteTransaction.doHandleRequest(FrontendReadWriteTransaction.java:189)
	at org.opendaylight.controller.cluster.datastore.FrontendTransaction.handleRequest(FrontendTransaction.java:141)
	at org.opendaylight.controller.cluster.datastore.AbstractFrontendHistory.handleTransactionRequest(AbstractFrontendHistory.java:154)
	at org.opendaylight.controller.cluster.datastore.LeaderFrontendState.handleTransactionRequest(LeaderFrontendState.java:210)
	at org.opendaylight.controller.cluster.datastore.Shard.handleRequest(Shard.java:462)
	at org.opendaylight.controller.cluster.datastore.Shard.handleNonRaftCommand(Shard.java:293)
	at org.opendaylight.controller.cluster.raft.RaftActor.handleCommand(RaftActor.java:270)
	at org.opendaylight.controller.cluster.common.actor.AbstractUntypedPersistentActor.onReceiveCommand(AbstractUntypedPersistentActor.java:31)
	at akka.persistence.UntypedPersistentActor.onReceive(PersistentActor.scala:170)
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497)
	at akka.persistence.UntypedPersistentActor.akka$persistence$Eventsourced$$super$aroundReceive(PersistentActor.scala:168)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183)
	at akka.persistence.UntypedPersistentActor.aroundReceive(PersistentActor.scala:168)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Which indicates we have rejected canCommit, to which the frontend
reacts by aborting, but the abort request does not hit persistence.
We need to handle this state and transition the transaction into
ABORTING state.

Change-Id: Ib5dcceb8aea5ae227daec77ee33fd73445b31c9d
Signed-off-by: Robert Varga <robert.varga@pantheon.tech>