Update patch set 8
Patch Set 8: Code-Review-1

When I try to run this with the latest master I get an error from the config subsystem bout missing capabilities.

2014-06-30 13:19:55.861 EDT [config-pusher] ERROR o.o.c.l.b.i.UncaughtExceptionPolicy - Thread Thread[config-pusher,5,main] died because of an uncaught exception
java.lang.IllegalStateException: Max wait for capabilities reached.Not enough capabilities for ConfigSnapshot{configSnapshot='<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><modules xmlns="urn:opendaylight:params:xml:ns:yang:controller:config"><module><type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc">prefix:remote-zeromq-rpc-server</type><name>remoter</name><port xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc">5666</port><dom-broker xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc"><type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom">prefix:dom-broker-osgi-registry</type><name>dom-broker</name>
                   </dom-broker>
               </module>
            </modules><services xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">
            </services>
        </data>
    ', capabilities=[urn:opendaylight:params:xml:ns:yang:controller:md:sal:common?module=opendaylight-md-sal-common&revision=2013-10-28, urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom:impl?module=opendaylight-sal-dom-broker-impl&revision=2013-10-28, urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom?module=opendaylight-md-sal-dom&revision=2013-10-28, urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc?module=odl-sal-dom-rpc-remote-cfg&revision=2013-10-28]}. Expected but not found: [urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc?module=odl-sal-dom-rpc-remote-cfg&revision=2013-10-28]
	at org.opendaylight.controller.netconf.persist.impl.ConfigPusher.getOperationServiceWithRetries(ConfigPusher.java:114) ~[na:na]
	at org.opendaylight.controller.netconf.persist.impl.ConfigPusher.pushConfigWithConflictingVersionRetries(ConfigPusher.java:90) ~[na:na]
	at org.opendaylight.controller.netconf.persist.impl.ConfigPusher.pushConfigs(ConfigPusher.java:68) ~[na:na]
	at org.opendaylight.controller.netconf.persist.impl.osgi.ConfigPersisterActivator$InnerCustomizer$1.run(ConfigPersisterActivator.java:156) ~[na:na]
	at java.lang.Thread.run(Thread.java:744) ~[na:1.7.0_51]
Caused by: org.opendaylight.controller.netconf.persist.impl.ConfigPusher$NotEnoughCapabilitiesException: Not enough capabilities for ConfigSnapshot{configSnapshot='<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><modules xmlns="urn:opendaylight:params:xml:ns:yang:controller:config"><module><type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc">prefix:remote-zeromq-rpc-server</type><name>remoter</name><port xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc">5666</port><dom-broker xmlns="urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc"><type xmlns:prefix="urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom">prefix:dom-broker-osgi-registry</type><name>dom-broker</name>
                   </dom-broker>
               </module>
            </modules><services xmlns="urn:opendaylight:params:xml:ns:yang:controller:config">
            </services>
        </data>
    ', capabilities=[urn:opendaylight:params:xml:ns:yang:controller:md:sal:common?module=opendaylight-md-sal-common&revision=2013-10-28, urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom:impl?module=opendaylight-sal-dom-broker-impl&revision=2013-10-28, urn:opendaylight:params:xml:ns:yang:controller:md:sal:dom?module=opendaylight-md-sal-dom&revision=2013-10-28, urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc?module=odl-sal-dom-rpc-remote-cfg&revision=2013-10-28]}. Expected but not found: [urn:opendaylight:params:xml:ns:yang:controller:md:sal:remote:rpc?module=odl-sal-dom-rpc-remote-cfg&revision=2013-10-28]
	at org.opendaylight.controller.netconf.persist.impl.ConfigPusher.getOperationService(ConfigPusher.java:152) ~[na:na]
	at org.opendaylight.controller.netconf.persist.impl.ConfigPusher.getOperationServiceWithRetries(ConfigPusher.java:107) ~[na:na]
	... 4 common frames omitted

Patch-set: 8
Label: Code-Review=-1