Update patch set 7
Patch Set 7: Code-Review-1

There are 2 problems remaining here:

1. Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact archetype.it:basic-karaf:zip:0.0.1-SNAPSHOT in central (http://repo1.maven.org/maven2/)

2. https://lists.opendaylight.org/pipermail/controller-dev/2016-May/012054.html : Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (failsafe-integration-tests) on project opendaylight-startup-archetype: Execution failsafe-integration-tests of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: projects/basic/project/basic/it/target/test-classes/it/pkg/it/BasicIT (wrong name: it/pkg/it/BasicIT)


1. only happens on the Gerrit, not locally. Unclear why, but it has something to do with Pax Exam not understanding http://blog2.vorburger.ch/2016/05/how-to-make-maven-archetype-plugin.html

2. happens locally as well for me (at least sometimes?), and should have been fixed by https://git.opendaylight.org/gerrit/#/c/40297/, but that had to be reverted.  So need to fix that first.

Patch-set: 7
Label: Code-Review=-1