Update patch set 7
Patch Set 7:

I pulled master then this patch, and I am getting the following build error: Failed tests: 
  RestGetOperationTest.getOperationsTest:274 expected:<200> but was:<500>
  RestGetOperationTest.getOperationsBehindMountPointTest:315 expected:<200> but was:<500>

Is there another required patch?

Patch-set: 7
Reviewer: Gerrit User 1778 <1778@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0